name: ada_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  # Dependencias principales
  sqflite: ^2.3.0
  path: ^1.8.3

  geolocator: ^13.0.0
  barcode_scan2: ^4.2.3
  connectivity_plus: ^6.1.4
  local_auth: ^2.1.8
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  equatable: ^2.0.5
  url_launcher: ^6.2.1
  bcrypt: ^1.1.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_svg: ^2.0.0
  uuid: ^4.0.0
  battery_plus: ^6.0.0
  device_info_plus: ^10.0.0
  permission_handler: ^11.0.0
  synchronized: ^3.1.0
  #workmanager: ^0.5.2


  # Para peticiones HTTP
  http: ^1.2.0

  # Para convertir JSON fácilmente
  json_annotation: ^4.8.1

  # Iconos de Cupertino
  cupertino_icons: ^1.0.8
  workmanager: ^0.9.0+3
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.1.1
  flutter_local_notifications: ^19.5.0
  showcaseview: ^5.0.1
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Para generar código JSON automáticamente
  build_runner: ^2.4.7
  json_serializable: ^6.7.0

  # Lints recomendados
  flutter_lints: ^5.0.0

  # Para cambiar nombre de la app
  rename: ^3.1.0

  # Para generar iconos (movido aquí desde dependencies)
  flutter_launcher_icons: ^0.13.1

# Configuración de iconos
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_bdp.png"

flutter:
  uses-material-design: true

  # Declarar assets
  assets:
    - assets/